### PR TITLE
Add two new web development books

### PR DESCRIPTION
**Pull request by mattmakai**
Add two new web development books, the free open source [Full Stack Python](https://www.fullstackpython.com/) as well as [The Full Stack Python Guide to Deployments](http://www.deploypython.com/).

### CODE REVIEW

**Comment by Junnplus** [comment]
Are two books already published?

**Comment by makaimc** [comment]
Yes, they are both already published.

On Thursday, April 28, 2016, 不好奇的喵 <notifications@github.com> wrote:

> Are two books already published?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Junnplus/awesome-python-books/pull/7#issuecomment-215620430>
>


-- 
Sent from my TI-83 Graphing Calculator

**Comment by mattmakai** [comment]
same question as for PR #4, any reason why not merged @Junnplus?

**Comment by Junnplus** [comment]
@mattmakai i think *Full Stack Python Guide to Deployments* can be merged, but *Full Stack Python* just a guide of learning python and provides something helpful resources.

**Pull request closed without merging**
